{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: retail-app
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.mysql.servicePort }}
      targetPort: {{ .Values.mysql.containerPort }}
  selector:
    app: mysql
{{- end }}

