{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: retail-app
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.redis.servicePort }}
      targetPort: {{ .Values.redis.containerPort }}
  selector:
    app: redis
{{- end }}

