apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: retail-app-readonly
  namespace: retail-app
subjects:
- kind: User
  name: bedrock-dev-view
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io

